import 'styles/style.css'
import Nav from 'ui/Navigation/Nav'
import Foot from 'ui/Navigation/Foot'

export const metadata = {
  title: 'Crib Network',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='h-[100vh]'>
        <Nav/>
        {children}
        <Foot/>
        </body>
    </html>
  )
}
